氷のギミック作成
tricore-as07/Slime pull request #10
Opened 2020-10-23 02:07 UTC by tricore-as07

・氷のギミックの作成
・プレイヤーが氷状態になった時に挙動が変わる部分の対応
・プレイヤーが氷状態になった時に炎と棘のギミックに当たった時の特殊処理の追加

2020-10-27 06:03 UTC, tricore-t-yui approved these changes
ざっと見LGTM

2020-10-27 07:47 UTC, tricore-as03 approved these changes
LGTM

2020-10-27 09:11 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
[Q]
どうしてstatic？
staticだったら頭文字大文字にしたほうがよかった気がする

2020-10-27 09:40 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
シーン上にプレイヤーは１つしかなく、取得にGetComponentを使用していたので
同じギミックをステージに複数置いた際に毎回GetComponentを実行しないようにと思ったのですが
このような使い方はあまりしない方がいいのでしょうか？

2020-10-27 09:45 UTC, tricore-as05 approved these changes

2020-10-27 09:45 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
天才です

2020-10-27 09:50 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
ほんまや！
スパゲティの元だこれ
安易なstaticやめてほしい

2020-10-27 09:50 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
それならそもそもOnTriggerEnterする前に、あらかじめIceGimmickにPlayerを設定してあげる人が必要です
また、その場合なら「ぶつかった人がただ一人しか存在しないプレイヤーそのものである」ことを判定するのにタグでプレイヤーかどうかを判定するのがおかしな話になります
タグ自体はプレイヤーコンポーネント以外も設定できるので
if(other.gameOjbect == player.gameObject)
とかならわかりますが

2020-10-27 09:53 UTC, tricore-t-yui requested changes

2020-10-27 09:53 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
ぶつかったその人がプレイヤーコンポーネントかどうか毎度判定するので、たしかに重くはあるけどEnterでplayerタグだった場合のみに走る処理だしGetComponent毎回でもいいんじゃないかな…
上記実装は時間がかかると思うので

2020-10-27 09:56 UTC, tricore-t-yui requested changes

2020-10-27 09:56 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
ゲーム走っている間一度でも保存したらずっとメモリに参照乗り続けるという問題もある

2020-10-28 02:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/IceGimmick.cs
> +    static Player player;           //プレイヤーのクラス
とりあえずstaticを使わない形に修正しました。

2020-10-29 02:43 UTC, tricore-t-yui approved these changes
LGTM

2020-10-29 02:43 UTC, merged