横田さんのブランチの内容の反映と不具合、足りなかった機能の追加
tricore-as07/Slime pull request #16
Opened 2020-10-30 03:21 UTC by tricore-as07

# 変更スクリプト
- Assets/MyGameAssets/Scripts/Player/Player.cs 
    - 初期化時、PhysicMaterialがnullだったら取得してくるようにしました。
    - 接地判定の問題を解決したので初期状態を落下状態にすることで開始直後に浮いていてもジャンプできる
不具合を修正しました。
- Assets/MyGameAssets/Scripts/Player/PlayerFreeFallState.cs 
    - 接地判定をEnterに加えてStayを加えることで初期状態を落下状態から始めても不具合が起きないようにしました
    - フックを伸ばす方向をPlayerSettingの値を使用してプレイヤーの前方方向から設定された角度方向にRayを飛ばすように
- Assets/MyGameAssets/Scripts/Utility/PlayerSettingsData.cs 
    - 触手を伸ばす方向を設定できるようにしました

# 新規追加スクリプト
- Assets/MyGameAssets/Scripts/Stage/ArchTriggerCreater.cs 
    - ステージで登り坂を実装するために使用するアーチ用のトリガーを作成します（接地判定に使用）

2020-10-30 03:28 UTC, tricore-t-yui requested changes
unityバージョン上げたならその旨も書きましょう

2020-10-30 03:28 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +        physicMaterial = physicMaterial ?? GetComponent<SphereCollider>().material;
[MUST]
ここでスフィアコライダーが確実にあるのを求めるならRequireComponentつけるか、なかった時のエラー表示を入れるべき

2020-10-30 04:57 UTC, tricore-as05 approved these changes
ArchTriggerCreaterが、
Debug用のクラスでどういう処理をするためのクラスなのかの説明を書いてあげてください。
口頭で聞いたのでApprove

2020-10-30 05:10 UTC, tricore-as03 approved these changes
nits一件あるけど、Approve

2020-10-30 05:10 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Stage/ArchTriggerCreater.cs
> +        GameObject gameObject = Instantiate(this.gameObject,transform.position,transform.rotation,transform.parent);
[nits]
名前がgameObjectだと自身が持ってるgameObjectと混乱しそうだから名前変えたほうがいいかも。
複製だからduplicateObjectかな。

2020-10-30 05:47 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +        physicMaterial = physicMaterial ?? GetComponent<SphereCollider>().material;
修正しました

2020-10-30 05:56 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/ArchTriggerCreater.cs
> +        GameObject gameObject = Instantiate(this.gameObject,transform.position,transform.rotation,transform.parent);
修正しました。

2020-11-04 03:45 UTC, tricore-t-yui approved these changes
LGTM

2020-11-04 03:46 UTC, merged