Level design preparation
tricore-as07/Slime pull request #17
Opened 2020-11-04 05:45 UTC by tricore-as07

# 変更スクリプト
- Assets/MyGameAssets/Scripts/Player/Gimmick/PlayerTentacle.cs 
    - 触手を伸ばすのを一瞬から時間をかけて伸ばすように変更しました。
- Assets/MyGameAssets/Scripts/Player/Player.cs 
    - 触手を引っ掛けられるフックの上にUIを表示するために使う変数を宣言
- Assets/MyGameAssets/Scripts/Player/PlayerFreeFallState.cs 
    - フックをアニメーションに対応
    - 使用できるフックにイベントを送るシステムの作成
- Assets/MyGameAssets/Scripts/Player/PlayerHookState.cs 
    - プレイヤークラスの変更の反映とスクリプトを見やすく
- Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondManager.cs 
    - 仮で設定していたステージ数をちゃんと取得してくるように
- Assets/MyGameAssets/Scripts/Stage/Gimmick/WindGimmick.cs 
    - ギミックの上方向に力が加わるように不具合修正
- Assets/MyGameAssets/Scripts/Utility/EventManager.cs 
    - イベントの追加
- Assets/MyGameAssets/Scripts/Utility/PlayerSettingsData.cs 
    - 設定項目の追加

# 新規追加スクリプト
- Assets/MyGameAssets/Scripts/UI/DebugWarningUI.cs 
    - デバッグ時にエラーを出すためのものです
    - 現状はフックが一定間隔を空けていないと出るものです。
- Assets/MyGameAssets/Scripts/UI/HookTarget.cs 
    - フックのターゲットに合わせてUIを表示します
- Assets/MyGameAssets/Scripts/Utility/SceneSetting.cs 
    - シーンごとの設定をもつスクリプト

2020-11-04 15:07 UTC, tricore-as03 requested changes

2020-11-05 01:41 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/Gimmick/PlayerTentacle.cs
> +            mediumPos = (player.transform.position + hook) / 2f;
修正しました

2020-11-05 13:40 UTC, tricore-as03 approved these changes
LGTM

2020-11-06 06:15 UTC, tricore-as05 approved these changes
nitsありますが、LGTM

2020-11-06 06:15 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Player/PlayerHookState.cs
> +            Context.playerTentacle.ExtendTentacle(
[nits]
改行されたままだとわかりずらいから以下のような感じでやるとよいかも

・引数の行の開始位置にスペースを空けてわかりやすくする
```
Context.playerTentacle.ExtendTentacle(
　　　Context.gameObject,
　　　joint.transform.position - new Vector3(0f,joint.transform.localScale.y * 0.5f),
　　　Context.playerSettingsData.ExtendTentacleTime);
```


・長い部分をまとめる
```
var 距離 = joint.transform.position - new Vector3(0f,joint.transform.localScale.y * 0.5f;
Context.playerTentacle.ExtendTentacle(Context.gameObject, 距離, Context.playerSettingsData.ExtendTentacleTime);
```

2020-11-06 06:15 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/DebugWarningUI.cs
> +            (HookPointTriggerRadius + HookPointTriggerRadius + player.transform.localScale.x)
[nits]
以下のように書くときれいかも
```
var 間隔 = HookPointTriggerRadius + HookPointTriggerRadius + player.transform.localScale.x
var mustOpenSqrDist = 間隔 * 間隔;
```

2020-11-06 06:15 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/HookTarget.cs
> +    [SerializeField] Player player = default;
[nits]
変数コメント

2020-11-10 07:39 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/HookTarget.cs
> +    [SerializeField] Player player = default;
修正しました

2020-11-10 07:40 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/DebugWarningUI.cs
> +            (HookPointTriggerRadius + HookPointTriggerRadius + player.transform.localScale.x)
修正しました

2020-11-10 07:40 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerHookState.cs
> +            Context.playerTentacle.ExtendTentacle(
修正しました

2020-11-13 02:55 UTC, merged