スキンに関する機能の実装
tricore-as07/Slime pull request #27
Opened 2020-12-03 05:57 UTC by tricore-as07

# 変更スクリプト
- Assets/MyGameAssets/Scripts/Player/Player.cs 
    - プレイヤーのスキンを変更するために見た目専用のゲームオブジェクトをプレイヤーに設定するように変更
- Assets/MyGameAssets/Scripts/SaveData/SaveDataManager.cs 
    - 現在選択されているスキンの種類をセーブするようの関数を追加実装
- Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondManager.cs 
    - ゲームクリア時にダイヤモンドの合計数を更新する
- Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondObject.cs 
    - ダイヤモンドを取得してゲームオーバーになった時に取得情報をリセットする処理を追加
- Assets/MyGameAssets/Scripts/Utility/EventManager.cs 
    - イベントを追加
- Assets/MyGameAssets/Scripts/Utility/SaveData.cs 
    - セーブデータに現在のスキンデータを追加

# 新規追加スクリプト
- Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondCounter.cs 
    - ダイヤモンドの総数を数えるクラス
- Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs 
    - スキンを選択するボタンに関する処理をするクラス
- Assets/MyGameAssets/Scripts/Utility/PlayerSkinData.cs 
    - プレイヤーのスキンとIDのScriptableObject
- Assets/MyGameAssets/Scripts/Utility/SkinManager.cs 
    - スキンの管理をする機能の実装

2020-12-03 07:04 UTC, tricore-as05 requested changes

2020-12-03 07:04 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +        None,                   //なし
[nits]
Noneいります？
もしこのNoneが解除されていないということを意味しているならLockに変えたほうがわかりやすいかと

UnlockType.Lockというのも変に感じるのであればフラグ用意するなりしたほうが良いかと

2020-12-03 07:04 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Utility/PlayerSkinData.cs
> +public class PlayerSkinData : ScriptableObject
[MUST]
全体に変数コメント、SerializeFieldの初期値が入ってないです

2020-12-03 07:04 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Utility/SkinManager.cs
> +{
[MUST]
こちらも変数コメント、SerializeFieldの初期値が入ってないです

2020-12-03 07:15 UTC, tricore-as03 requested changes

2020-12-03 07:15 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/SaveData/SaveDataManager.cs
> +    public List<DiamondAcquisitionData> GetDiamondAcquisitionDataList()
[MUST]
Listでそのまま受け取ったら外部で自由に書き換えができてしまうので、読み取り専用で取得するようにする。
IReadOnlyListを使えば読み取り専用で受け取れる。AddとかRemoveができなくなる。
```
public IReadOnlyList<DiamondAcquisitionData> GetDiamondAcquisitionDataList()
{
    return saveData.stageSaveData.diamondAcquisitionDataList;
}
```

2020-12-03 07:15 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
RequireComponentはそのコンポーネントが同じオブジェクト内に一緒にアタッチされていることを強制するための機能です。
そのコンポーネントの参照が必要なのであれば、SerializeFieldは必要かと。

2020-12-03 07:20 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
強制されているのであればGetComponentだけでいいのでは？
したのほうにGetComponentされてありますけど

2020-12-03 07:24 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +    GameObject playerLooks = default;                                           //プレイヤーの見た目のオブジェクト
今はスキンとしての役割しかありませんが、後のブラッシュアップで見た目の変化とプレイヤーの物理の処理を分ける予定で見た目のオブジェクトとして使用しようと思っていたのでこの命名になりました。

2020-12-03 07:24 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
失礼しました。
GetComponentを見落としていました。

2020-12-03 07:27 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
ボタンが今のところ２０個あり、同じオブジェクトの参照を持ってくるだけなのでSerializefieldで持ってきています。
しかし、スキンを追加する際などにインスペクター上で設定を忘れていてもエラーが出ないように念のためのGetComponentが下に書いてあるといった感じです。
わかりにくくて申し訳ありません。

2020-12-03 07:27 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +    GameObject playerLooks = default;                                           //プレイヤーの見た目のオブジェクト
となると、ChangeSkinではなくChangeLooksに変えないといけないところがありそうですね

2020-12-03 07:29 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
それならわざわざ参照させなくてもGetComponent統一でいい気がします
それで極端に重くなってしまうのであれば、SerializeFieldでも問題ないと思いますが

2020-12-03 07:29 UTC, tricore-as03 requested changes

2020-12-03 07:29 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Utility/SkinManager.cs
> +        return skinDictionary[id];
[MUST]
キーが無かったとかで正しく値が取得できなかった場合に日本語でエラーが表示されるようにしてください。
DictionaryのTryGetValue関数を使えば取得に成功したかどうかをboolで受け取れるので、それを使うと良いかと。
下の44行目も同様に。

2020-12-03 07:37 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +    GameObject playerLooks = default;                                           //プレイヤーの見た目のオブジェクト
プレイヤーの見た目の変化の処理をする時にこのオブジェクトの参照を使用すると思うのでゲームオブジェクトはこの名前ですが、ChangeSkinはスキンの変更をしているのでこの名前で特に問題はない気がします。
おそらく見た目の変化処理の際にChangeLooksBy~といった名前を使用する予定なので似たような名前の混在を避けるためにもなると思います。

2020-12-03 07:39 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
できる事ならGetComponentは使用するべきではないと思っていたのですが大丈夫なのでしょうか？

2020-12-03 07:44 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Player/Player.cs
> +    GameObject playerLooks = default;                                           //プレイヤーの見た目のオブジェクト
わかりずらくて申し訳ない
ここで言ってたChangeSkinは、折本くんが言ってるChangeSkin()もそうですが、
SubjectType.OnChangeSkinのChangeSkinの部分なども含めたつもりで言っていました。
スキンだけではないのであれば、これもSubjectType.OnChangeLooksとかになるのでは？と思ったので

折本がいま言っているChangeSkinに関してはそちらで問題ないかと思います

2020-12-03 07:50 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
重ねて申し訳ない
たしか最初の方にGetComponentとするよりかはSerializeFieldで取ってきた方がいいよっていうのを俺が言って、たぶんそのせいで迷ってるのかと思うけど頻繁に通らなければGetComponent使っても問題ないかと思います。
これはたぶん生成時だから問題ないかと

2020-12-04 07:19 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] Button button;
このスクリプトをアタッチしているオブジェクトをプレハブにしてプレハブでSerializeFieldにあらかじめ
Buttonをアタッチする形で修正しました

2020-12-04 07:19 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +    [SerializeField] SkinId id;                                 //ボタンが押された時に変更されるスキン
修正しました

2020-12-04 07:20 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/UI/SkinSelectButton.cs
> +        None,                   //なし
コメントで分かりやすくなるように修正しました。

2020-12-04 07:21 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/PlayerSkinData.cs
> +public class PlayerSkinData : ScriptableObject
修正しました

2020-12-04 07:23 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/SkinManager.cs
> +{
修正しました

2020-12-04 07:24 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/SaveData/SaveDataManager.cs
> +    public List<DiamondAcquisitionData> GetDiamondAcquisitionDataList()
修正しました

2020-12-04 07:25 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/SkinManager.cs
> +        return skinDictionary[id];
修正しました

2020-12-04 07:36 UTC, tricore-as03 approved these changes
LGTM

2020-12-04 08:06 UTC, tricore-as05 approved these changes
LGTM

2020-12-04 08:10 UTC, merged