足りないエフェクトの追加実装
tricore-as07/Slime pull request #54
Opened 2021-02-18 05:25 UTC by tricore-as07

# 実装内容
- 足りないエフェクトの作成
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/FX_Blizzard_Cloud_01.prefab 
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/FX_Blizzard_Snow_02.prefab 
        - 凍っている状態の時にプレイヤーが通ったところに出るエフェクト
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/FX_Cartoony_Jump_02.prefab 
        - 壁や床に衝突した時のエフェクト
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/FX_Sparkle_Orbit_03.prefab 
        - プレイヤーが凍る時のエフェクト
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/FX_SwordStab_02.prefab 
        - ダイヤを取った時のエフェクト
    - Assets/MyGameAssets/GraphicPrefabAndResources/Effect/HookEffect.prefab 
        - フックに引っ掛けた時のエフェクト

- ポストプロセスの追加
    - Assets/MyGameAssets/GraphicPrefabAndResources/Post-processing Profile.asset 
        - ポストプロセスの設定ファイル

- 新規実装のスクリプトの内容
    - Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs 
        - プレイヤーに追従する
    - Assets/MyGameAssets/Scripts/Player/Gimmick/PlayerTentacle.cs 
        - フックに引っ掛けた時にエフェクトを生成する機能の実装
    - Assets/MyGameAssets/Scripts/Player/Player.cs 
        - プレイヤーが凍った時にエフェクトを生成する機能の実装
        - 壁や床に衝突した時にエフェクトを生成する機能の実装
    - Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondObject.cs 
        - ダイヤを取った時にエフェクトを生成する機能の実装

2021-02-18 05:32 UTC, tricore-as05 requested changes

2021-02-18 05:32 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs
> +        player = GameObject.FindGameObjectWithTag(TagName.Player);
[MUST]
何度もplayerをFindしてる気がするからどっかにまとめたほうがよさそう

2021-02-18 05:41 UTC, tricore-t-yui requested changes

2021-02-18 05:41 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs
> +        player = GameObject.FindGameObjectWithTag(TagName.Player);
[MUST]
Find系列の関数は超重いので可能な限り避けてください

2021-02-24 03:03 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs
> +        player = GameObject.FindGameObjectWithTag(TagName.Player);
修正しました

2021-02-24 03:03 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs
> +        player = GameObject.FindGameObjectWithTag(TagName.Player);
修正しました

2021-02-24 03:25 UTC, tricore-as03 requested changes

2021-02-24 03:25 UTC, tricore-as03 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +    }
[Q]
これplayerがnullだった場合に、自分自身でGetPlayerを呼び続けて無限ループになりそうな気がするのですが問題ないのでしょうか。

2021-02-24 03:26 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
[q]
無限ループしない？
あとプレイヤー自体がシングルトンにするのではなくオーナークラスだけが存在するのはよく分からない…
複数のインスタンスの参照だけするクラスが存在するならともかく

2021-02-24 03:31 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +    }
検索の一括置換してしまっていました修正します。

2021-02-24 03:33 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
検索の一括置換してしまっていました修正します。
プレイヤーはシングルトンにするのはあまり良く無いと思っていました。

2021-02-24 03:35 UTC, tricore-as05 reviewed
PlayerOwnerのプレイヤーと取り方がわからないのでそこだけ答えてもらえると

2021-02-24 03:35 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondObject.cs
> +    [SerializeField] GameObject getDiamondEffect = default;
[nits]
ここだけコメントがないのも不自然なので、入れるだけ入れといてください

2021-02-24 03:35 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +    /// <returns></returns>
[nits]
`<returns></returns>`を残すなら何が返ってくるのか追記したほうがいいです

2021-02-24 03:35 UTC, tricore-as05 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
[Q]
[SerializeField]とかで取ってくるならわかるんですが、どうやってplayerとってきてます？

2021-02-24 03:39 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
プレイヤーをシングルトンにするのが良くないのは、プレイヤーが増える可能性がある場合ですね
シングルトンが悪い、というわけではないです
プレイヤーにアクセスするだけの存在として、一人しかいてほしくないのでシングルトンにするならPlayerOwnerは設計的には正しいけど、最初の指摘通り複数存在するならまとめたほうがよさそうです
今はプレイヤーのみしかないなら現状の実装でも良さそうです
Ownerという名称には疑問が残るところですが
アクセサな気がする

2021-02-24 03:57 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
一括置換で間違って書き換わっていました。
修正しました。

2021-02-24 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +    /// <returns></returns>
修正しました。

2021-02-24 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/Gimmick/DiamondObject.cs
> +    [SerializeField] GameObject getDiamondEffect = default;
修正しました。

2021-02-24 03:58 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerOwner.cs
> +            player = PlayerOwner.Inst.GetPlayer();
名前を修正しました

2021-02-24 03:59 UTC, tricore-as05 approved these changes
LGTM

2021-02-24 04:01 UTC, tricore-as07 commented
プレイヤーのゲームオブジェクトを取得する方法ですが、
プレイヤーでステートマシンを使用する際にpartialを使っていたため、プレイヤー自身をシングルトンにすることは
出来ませんでした。
なので、PlayerAccessorだけをシングルトンにしてそこからプレイヤーのゲームオブジェクトを取得するように実装しました。

2021-02-24 04:06 UTC, tricore-t-yui reviewed
nits２件だけどLGTM

2021-02-24 04:06 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Effect/FollowPlayer.cs
> +    GameObject player;          //プレイヤーのオブジェクト
[nits]
この使い方ならキャッシュするのはtransformでいいです
修正必須ではないです
豆知識として、「.transform」も「.position」も重いということは覚えておいていただけると

2021-02-24 04:06 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerAccessor.cs
> +    public GameObject GetPlayer()
[nits]
修正必須ではないですが、プロパティではなく関数だと、取得以外にも何かしているのかな？と勘ぐられるので、値取得だけするものはプロパティにするのが最近の風潮のようです
そのため、プロパティに何か処理を入れると超弾圧されます

2021-02-24 04:07 UTC, tricore-t-yui approved these changes
LGTM

2021-02-24 04:07 UTC, tricore-as03 approved these changes

2021-02-25 02:06 UTC, merged