デモシーン（モック）の作成
tricore-as07/Slime pull request #7
Opened 2020-10-08 01:23 UTC by tricore-as07

・ライブラリ関係での警告を無くしました
・シーンが始まって入力がされたらゲームが開始されるようにしました
・ゴール地点の判定を取れるようにしました
・プレイヤーが設置している時にジャンプできるようにしました
・カメラがプレイヤーを追いかけるようにしました

UniRxを使ったイベントの部分は後ほどイベントマネージャーを作ってアクセスしやすくする予定です。

2020-10-08 07:44 UTC, tricore-as05 approved these changes
LGTM

2020-10-08 08:35 UTC, tricore-t-yui requested changes

2020-10-08 08:35 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/GameStartTap.cs
> +public class GameStartTap : MonoBehaviour
[MUST]
クラス名としては意味が通らない
「ゲームが開始された時のタップ」という意味になる
このクラスの役割は想像できない

2020-10-09 08:27 UTC, tricore-as07 commented
イベント周りの修正と一緒にフック処理のステートも追加しました。

2020-10-09 08:28 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/GameStartTap.cs
> +public class GameStartTap : MonoBehaviour
修正しました。

2020-10-09 08:56 UTC, tricore-t-yui requested changes

2020-10-09 08:56 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +    }
[MUST]
空関数には必ずコメントを

2020-10-09 08:56 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +        get {
[MUST]
改行ルール違反

2020-10-09 08:56 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Stage/GoalArea.cs
> +        if (other.transform.tag == "Player")
[MUST]
タグ名の直入力は危険

2020-10-09 08:56 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    /// <summary>
[MUST]
内部コードが同じで返り値の型が違うだけならジェネリックを使う

2020-10-09 08:58 UTC, tricore-as05 approved these changes
LGTM

2020-10-09 09:01 UTC, tricore-as03 approved these changes
LGTM

2020-10-10 08:57 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerNormalState.cs
> +
修正しました

2020-10-10 09:12 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/GoalArea.cs
> +        if (other.transform.tag == "Player")
修正しました。

2020-10-10 09:12 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +        get {
修正しました。

2020-10-10 09:12 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +    }
修正しました。

2020-10-13 00:59 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Stage/GoalArea.cs
> +        if (other.transform.tag == "Player")
修正しました。

2020-10-13 03:16 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    /// <summary>
修正しました。

2020-10-13 03:18 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    /// <summary>
ジェネリックを使うように修正したのではなく、イベントマネージャーの設計から
修正しているので確認お願いします。

2020-10-13 05:52 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    /// <summary>
修正しました。
ジェネリックを使用する形ではなく、イベントマネージャーの仕組みを変えているので
確認をお願いします。

2020-10-13 08:53 UTC, tricore-t-yui requested changes

2020-10-13 08:53 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +    }
[nits]
関数の中に書きたい

2020-10-13 08:53 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +        {
[IMO]
protected internal virtual void OnCollisionEnter(Collision collision){}
にするか
{
// 処理なし
}
にするかのどちらかじゃないかな

2020-10-13 08:53 UTC, tricore-t-yui commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    public void CreateSubject(SubjectType type)
[Q]
Subscribeしたときにサブジェクトなかったら自動追加にすればpublic開放いらなくないかな

2020-10-13 09:13 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    public void CreateSubject(SubjectType type)
イベントを呼ぶ側がサブジェクトを作るべきだという概念に囚われすぎてました。
確かに必要ないと思います。

2020-10-13 09:14 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Player/PlayerStateMachine.cs
> +        {
修正しました。

2020-10-13 09:14 UTC, tricore-as07 commented on Assets/MyGameAssets/Scripts/Utility/EventManager.cs
> +    public void CreateSubject(SubjectType type)
修正しました。

2020-10-15 09:32 UTC, tricore-t-yui approved these changes
Approve

2020-10-15 09:32 UTC, merged